### ISSUE TITLE
AKMOD_PRIVKEY_20230518 is not documented

### ISSUE THREAD

**Issue by Perpixel** [ublue-os/nvidia#136]
Build fail without much information on the missing AKMOD_PRIVKEY_20230518 secret. Should this be changed back to AKMOD_PRIVKEY or documented and renamed to something more meaning full?

**Comment by bsherman** [comment]
Our expected use case for this repo was not for others to use its contents, or clone it for custom use, rather to build OCI images which are used as FROM sources for downstream images. But apparently, it is is getting cloned and used.

However, it's a good point that if this fail due to a missing secret it could be confusing.  No the secret probably won't be renamed, but you are welcome to create a PR which adds to the README to explain that the key is provided via a secret in our github actions workflows. I'd suggest that a user cloning this just change the secret variable to something of their choice, but they of course use this variable name.
